apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: updatehub-ui
  labels:
    service: updatehub-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: updatehub-ui
    spec:
      containers:
      - name: updatehub-ui
        image: gustavosbarreto/uhmicro-ui
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
